### ISSUE TITLE
thresholds for CPU usage

### ISSUE THREAD

**Issue by fantapereira** [zevenet/zevenet-nagios-plugins#5]
Hello:
         While running the command, i'm getting constant "critical" if i set the parameters (While assuming that Critical Higher than warning). We need to get alerted if the CPU usage is greater than 95%:

> --warning 90 --critical 95
ZEVENET_CPU CRITICAL - Zevenet ADC Load Balancer CPU usage is 0 % (100 % idle) | Idle=100%;90;95 IOWait=0%;; IRQ=0%;; Nice=0%;; SoftIRQ=0%;; Sys=0%;; Usage=0%;; User=0%;; Total=100%;;

if i set the thresholds Warning 100 and critical 101 i got a CPU ok

> --warning 90 --critical 95
ZEVENET_CPU CRITICAL - Zevenet ADC Load Balancer CPU usage is 0 % (100 % idle) | Idle=100%;90;95 IOWait=0%;; IRQ=0%;; Nice=0%;; SoftIRQ=0%;; Sys=0%;; Usage=0%;; User=0%;; Total=100%;;

I need some clarification about how to set the parameters correctly.

Thanks in advance.

**Comment by emiliocampos-zevenet** [comment]
Hi @fantapereira 

check_zevenet.cpu.pl manages the idle CPU value, by default 100% if appliance is doing nothing, and it is related with the threshold field, threshold format is described as follows:

https://www.monitoring-plugins.org/doc/guidelines.html#THRESHOLDFORMAT

A posibble configuration would be:
./check_zevenet_cpu.pl  -H 192.168.100.134 -z HOLAMUNDO -w @10:20 -c @0:9

it will be warning if the IDLE value is between 0% and 9% and it will be warning if idle value is between 10% and 20%, So if your CPU is totally used the idle will be 0%.

Thanks!

**Comment by fantapereira** [comment]
Excellent, i got now an OK message

>  -w @10:20 -c @0:9
ZEVENET_CPU OK - Zevenet ADC Load Balancer CPU usage is 0.5 % (99.5 % idle) | Idle=99.5%;@1020;@09 IOWait=0%;; IRQ=0%;; Nice=0%;; SoftIRQ=0%;; Sys=0.25%;; Usage=0.5%;; User=0.25%;; Total=100%;;

**Comment by emiliocampos-zevenet** [comment]
Thanks for confirmation.
