### ISSUE TITLE
Inconsequent use of defining threshold values

### ISSUE THREAD

**Issue by jvandermeulen** [zevenet/zevenet-nagios-plugins#6]
Some Zevenet plugins seem to suffer from inconsequent use defining WARNING and CRITICAL values.

Let's focus on "CPU Usage" as an example and bare the Nagios Plugin Development Guidelines (https://nagios-plugins.org/doc/guidelines.html#THRESHOLDFORMAT) in mind...

This URL https://www.zevenet.com/knowledge-base/howtos/monitoring-zevenet-nagios/#Test_plugin_manually uses warning and critical like this: `-w 20 -c 10`. This would normally mean issue a warning is raised if calculated value is above 20 and a critical is raised if value is above 10...
Apparently this is not what you intended. You want to reverse  the logic.

However this config file
https://github.com/zevenet/zevenet-nagios-plugins/blob/master/etc/zevenet_services.cfg#L31-L36
uses warning and critical like this: `-w 20: -c 10:` which seems to fit the reverse logic explained in the Plugin Development Guidelines. 

To my surprise the actual plugin code contains even two other variants

1. https://github.com/zevenet/zevenet-nagios-plugins/blob/master/libexec/check_zevenet_cpu.pl#L34-L38  Return CRITICAL if CPU usage is higher than CRITICAL treshold. Return WARNING if CPU usage is higher than WARNING treshold and below CRITICAL. That would mean `-w 80 -c 90`
and 
1. according to these lines https://github.com/zevenet/zevenet-nagios-plugins/blob/master/libexec/check_zevenet_cpu.pl#L105-L123 it seems to expect a **range** like this -w <MIN>:<MAX> that would look like `-w 0:80 -c -0:90` or `-w@80:90 -c@90:100`

**Comment by emiliocampos-zevenet** [comment]
Hi @jvandermeulen, yes you are totally right, the used values are related to the threshold, but the format described in the output help is not consistent with the needed information by the checks, I will check it and commit the changes as needed, I will keep opened this issue until then.

Thanks for your reports

**Comment by emiliocamposmartin** [comment]
Hi, commit added to check_zevenet_cpu.pl in order to clarify the usage and work with thresholds as expected, also added support to modify the management port (default 444), we will proceed to close the ticket, if you have more proposals please open a new one.

Thanks!

**Comment by emiliocampos-zevenet** [comment]
Hi, commit added to check_zevenet_cpu.pl in order to clarify the usage and work with thresholds as expected, also added support to modify the management port (default 444), we will proceed to close the ticket, if you have more proposals please open a new one.

Thanks!
